name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest matplotlib numpy
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests
      run: |
        python -m pytest test_model.py -v
        
    - name: Upload augmentation examples
      uses: actions/upload-artifact@v3
      with:
        name: augmentation-examples
        path: augmentation_examples.png
        retention-days: 1